name: Auto-Tag Release

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Auto-tag release
      uses: Klemensas/action-autotag@stable
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
