name: Auto-Tag Release

on:
  push:
    branches: [ main ]

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Auto-tag release
      uses: Klemensas/action-autotag@stable
